# Generated by Django 4.2 on 2025-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
